name: wifi_null_safety
description: Flutter plugin providing WiFi.
homepage: https://github.com/once10301/wifi_null_safety
version: 0.2.0

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.ly.wifi
        pluginClass: WifiPlugin
      ios:
        pluginClass: WifiPlugin
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.0"
